In [1]:
import pandas as pd

#Stage1.Looking at the Krankenhausverzeichnis_2023

In [2]:
sheet_to_df_map = pd.read_excel("/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/krankenhausverzeichnis_2023.xlsx", sheet_name=None)

In [3]:
df = pd.read_excel("/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/krankenhausverzeichnis_2023.xlsx")

In [4]:
xls = pd.ExcelFile("/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/krankenhausverzeichnis_2023.xlsx")
xls.sheet_names

['Titelblatt',
 'Impressum',
 'Inhalt',
 'Vorbemerkungen',
 ' KHV_2023',
 'RHV_2023',
 'DSB_KHV_2023',
 'DSB_RHV_2023',
 'Land',
 'Kreis',
 'Statistische Ämter']

In [5]:
df = pd.read_excel("/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/krankenhausverzeichnis_2023.xlsx", sheet_name="Kreis")

In [6]:
sheet_to_df_map[" KHV_2023"].head()

,Zurück zum Inhalt,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171
0,Verzeichnis der Krankenhäuser (KHV_2023),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Land,Kreis,Gemeinde,Adresse_Name,Adresse_Name_Standort,Adresse_Strasse_Standort,Adresse_Haus-Nr._Standort,Adresse_Postleitzahl_Standort,Adresse_Ort_Standort,Telefonvorwahl -nummer,...,3750.0,3751.0,3752.0,3753.0,3754.0,3755.0,3756.0,3757.0,3758.0,3759.0
2,01,001,000,DIAKO Krankenhaus gGmbH,DIAKO Krankenhaus gGmbH,Knuthstraße,1,24939,Flensburg,0461 812-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Fachklinik f...,"DIAKO Fachklinik für Psychiatrie, Psychosomati...",Knuthstraße,1,24939,Flensburg,0461 812-1701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Ältere Flensburg,Marienhölzungsweg,8,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
sheet_to_df_map[" KHV_2023"].columns

Index(['Zurück zum Inhalt', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9',
       ...
       'Unnamed: 162', 'Unnamed: 163', 'Unnamed: 164', 'Unnamed: 165',
       'Unnamed: 166', 'Unnamed: 167', 'Unnamed: 168', 'Unnamed: 169',
       'Unnamed: 170', 'Unnamed: 171'],
      dtype='str', length=172)

In [8]:
sheet_to_df_map[" KHV_2023"].shape

(2785, 172)

In [9]:
raw = pd.read_excel(xls, sheet_name=" KHV_2023", header=None)  #solving the issue with the headers
raw.head(10)

,0,1,2,3,4,5,6,7,8,9,...,162,163,164,165,166,167,168,169,170,171
0,Zurück zum Inhalt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Verzeichnis der Krankenhäuser (KHV_2023),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Land,Kreis,Gemeinde,Adresse_Name,Adresse_Name_Standort,Adresse_Strasse_Standort,Adresse_Haus-Nr._Standort,Adresse_Postleitzahl_Standort,Adresse_Ort_Standort,Telefonvorwahl -nummer,...,3750.0,3751.0,3752.0,3753.0,3754.0,3755.0,3756.0,3757.0,3758.0,3759.0
3,01,001,000,DIAKO Krankenhaus gGmbH,DIAKO Krankenhaus gGmbH,Knuthstraße,1,24939,Flensburg,0461 812-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Fachklinik f...,"DIAKO Fachklinik für Psychiatrie, Psychosomati...",Knuthstraße,1,24939,Flensburg,0461 812-1701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Ältere Flensburg,Marienhölzungsweg,8,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Erwachsene Flensburg,Marienhölzungsweg,21,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für KJP (Villa Paletti),Marienhölzungsweg,68,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Psychosomatik Flensburg,Nerongsallee,5,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,01,001,000,Katharinen Hospiz am Park,Katharinen Hospiz am Park,Mühlenstraße,1,24937,Flensburg,0461 503230,...,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.shape

(403, 3)

In [11]:
df = pd.read_excel(xls, sheet_name=" KHV_2023", header= 2, na_values=["-"])  #the right header found
df.head()

,Land,Kreis,Gemeinde,Adresse_Name,Adresse_Name_Standort,Adresse_Strasse_Standort,Adresse_Haus-Nr._Standort,Adresse_Postleitzahl_Standort,Adresse_Ort_Standort,Telefonvorwahl -nummer,...,3750,3751,3752,3753,3754,3755,3756,3757,3758,3759
0,1.0,1.0,0.0,DIAKO Krankenhaus gGmbH,DIAKO Krankenhaus gGmbH,Knuthstraße,1,24939.0,Flensburg,0461 812-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Fachklinik f...,"DIAKO Fachklinik für Psychiatrie, Psychosomati...",Knuthstraße,1,24939.0,Flensburg,0461 812-1701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Ältere Flensburg,Marienhölzungsweg,8,24939.0,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Erwachsene Flensburg,Marienhölzungsweg,21,24939.0,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für KJP (Villa Paletti),Marienhölzungsweg,68,24939.0,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.shape

(2783, 172)

In [13]:
df.columns

Index([                         'Land',                         'Kreis',
                            'Gemeinde',                  'Adresse_Name',
               'Adresse_Name_Standort',      'Adresse_Strasse_Standort',
           'Adresse_Haus-Nr._Standort', 'Adresse_Postleitzahl_Standort',
                'Adresse_Ort_Standort',        'Telefonvorwahl -nummer',
       ...
                                '3750',                          '3751',
                                '3752',                          '3753',
                                '3754',                          '3755',
                                '3756',                          '3757',
                                '3758',                          '3759'],
      dtype='object', length=172)

In [14]:
text_only = [c for c in df.columns if not str(c).isdigit()] # excluding data about bed counts per Fachabteilung/columns named as digits
hospitals = df[text_only].copy()
hospitals.shape

(2783, 22)

In [15]:
hospitals.head()

,Land,Kreis,Gemeinde,Adresse_Name,Adresse_Name_Standort,Adresse_Strasse_Standort,Adresse_Haus-Nr._Standort,Adresse_Postleitzahl_Standort,Adresse_Ort_Standort,Telefonvorwahl -nummer,...,Traeger,T_Name,EinrichtungsTyp,Allgemeine_Notfallversorgung,Spezielle_Notfallversorgung_Schwerverletzte,Spezielle_Notfallversorgung_Kinder,Spezielle_Notfallversorgung_Spezial,Spezielle_Notfallversorgung_Schlaganfall,Spezielle_Notfallversorgung_Durchblutung_Herz,INSG
0,1.0,1.0,0.0,DIAKO Krankenhaus gGmbH,DIAKO Krankenhaus gGmbH,Knuthstraße,1,24939.0,Flensburg,0461 812-0,...,2.0,DIAKO Krankenhaus gGmbH,2.0,2.0,1.0,1.0,2.0,1.0,2.0,400.0
1,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Fachklinik f...,"DIAKO Fachklinik für Psychiatrie, Psychosomati...",Knuthstraße,1,24939.0,Flensburg,0461 812-1701,...,2.0,DIAKO Nordfriesland gGmbH,2.0,0.0,2.0,2.0,2.0,2.0,2.0,87.0
2,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Ältere Flensburg,Marienhölzungsweg,8,24939.0,Flensburg,04671 408-0,...,2.0,DIAKO Nordfriesland gGmbH,2.0,0.0,2.0,2.0,2.0,2.0,2.0,0.0
3,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Erwachsene Flensburg,Marienhölzungsweg,21,24939.0,Flensburg,04671 408-0,...,2.0,DIAKO Nordfriesland gGmbH,2.0,0.0,2.0,2.0,2.0,2.0,2.0,0.0
4,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für KJP (Villa Paletti),Marienhölzungsweg,68,24939.0,Flensburg,04671 408-0,...,2.0,DIAKO Nordfriesland gGmbH,2.0,0.0,2.0,2.0,2.0,2.0,2.0,0.0

In [16]:
hospitals["EinrichtungsTyp"].value_counts(dropna=False)

EinrichtungsTyp
2.0    2352
4.0     230
3.0     108
1.0      86
5.0       5
NaN       2
Name: count, dtype: int64

In [17]:
#1 -Hochschulklinik , 2 -Plankrankenhaus , 3- Krankenhaus mit Versorgungsvertrag, 4- Krankenhaus ohne Versorgungsvertrag , 5- Bundeswehrkrankenhäuser

In [18]:
# keeping every type of a hospital, except for a private clinic
hospitals_full_type = hospitals.copy()    # a copy of the pre-filter version

hospitals = hospitals[hospitals["EinrichtungsTyp"].isin([1, 2, 3, 5])].copy()

print(hospitals["EinrichtungsTyp"].value_counts(dropna=False))

EinrichtungsTyp
2.0    2352
3.0     108
1.0      86
5.0       5
Name: count, dtype: int64

In [19]:
print(hospitals.shape)

(2551, 22)

#Stage 2. Looking at population_by_age_series.csv

In [20]:
csv_path = "/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/population_by_age_kreis_series.csv"

In [21]:
columns = [
    "date",
    "kreis_code",
    "kreis_name",
    "age_group",
    # "Insgesamt" group (all nationalities):
    "total_all",
    "total_male",
    "total_female",
    # "deutsch" group:
    "german_all",
    "german_male",
    "german_female",
    # "ausländisch" group:
    "foreign_all",
    "foreign_male",
    "foreign_female",
]

population = pd.read_csv(
    csv_path,
    skiprows=8,
    header=None,
    names=columns,
    encoding="latin1",
    sep=";",
    na_values=["-"]
)
population.head()

,date,kreis_code,kreis_name,age_group,total_all,total_male,total_female,german_all,german_male,german_female,foreign_all,foreign_male,foreign_female
0,31.12.2011,DG,Deutschland,unter 3 Jahre,2007147,1028888,978259,1920373,984386,935987,86774,44502,42272
1,31.12.2011,DG,Deutschland,3 bis unter 6 Jahre,2056777,1055634,1001143,1969110,1010506,958604,87667,45128,42539
2,31.12.2011,DG,Deutschland,6 bis unter 10 Jahre,2819988,1446549,1373439,2690250,1379822,1310428,129738,66727,63011
3,31.12.2011,DG,Deutschland,10 bis unter 15 Jahre,3889094,1994982,1894112,3604302,1849308,1754994,284792,145674,139118
4,31.12.2011,DG,Deutschland,15 bis unter 18 Jahre,2369946,1216198,1153748,2157004,1106559,1050445,212942,109639,103303

In [22]:
#there're extra rows under "the kreis_code" and "kreis_name", e.g. Deutschland, that I have to get rid of

In [23]:

population_raw = population.copy()

population = population[population["kreis_code"].astype(str).str.len() == 5].copy()

print(population.shape)

(41448, 13)

In [24]:
print(population["kreis_code"].nunique(), "unique Kreise")

471 unique Kreise

In [25]:
# The result doesn't sound right: 471 unique Kreise is too many.

In [26]:
population_new= population.dropna(subset=['total_all'])

In [27]:
print(population_new["kreis_code"].nunique(), "unique Kreise") # the result looks good

401 unique Kreise

In [28]:
population.head()

,date,kreis_code,kreis_name,age_group,total_all,total_male,total_female,german_all,german_male,german_female,foreign_all,foreign_male,foreign_female
44,31.12.2011,01001,"Flensburg, kreisfreie Stadt",unter 3 Jahre,2138,1072,1066,2071,1044,1027,67,28,39
45,31.12.2011,01001,"Flensburg, kreisfreie Stadt",3 bis unter 6 Jahre,1992,1046,946,1920,1007,913,72,39,33
46,31.12.2011,01001,"Flensburg, kreisfreie Stadt",6 bis unter 10 Jahre,2584,1332,1252,2504,1290,1214,80,42,38
47,31.12.2011,01001,"Flensburg, kreisfreie Stadt",10 bis unter 15 Jahre,3543,1836,1707,3408,1765,1643,135,71,64
48,31.12.2011,01001,"Flensburg, kreisfreie Stadt",15 bis unter 18 Jahre,2271,1161,1110,2173,1108,1065,98,53,45

#Stage 3. Preparing the files for merging

##first - the file Krankenhausverzeichnis_2023

In [29]:
hospitals["kreis_code"] = (
    hospitals["Land"].astype(int).astype(str).str.zfill(2)
    + hospitals["Kreis"].astype(int).astype(str).str.zfill(3)
)

In [30]:
print(hospitals[["Land", "Kreis", "kreis_code"]].head(6))

   Land  Kreis kreis_code
0   1.0    1.0      01001
1   1.0    1.0      01001
2   1.0    1.0      01001
3   1.0    1.0      01001
4   1.0    1.0      01001
5   1.0    1.0      01001

In [31]:
print(hospitals["kreis_code"].str.len().value_counts())

kreis_code
5    2551
Name: count, dtype: int64

In [32]:
print("\nUnique Kreise:", hospitals["kreis_code"].nunique()) 
# problematic: there should be less Kreise. Issue: Berlin and Hamburg are divided into Bezirke instead of representing a single Kreis

Unique Kreise: 444

In [33]:
hospitals = hospitals[~hospitals["Land"].astype(int).isin([2, 11])].copy()
print(hospitals.shape)

(2415, 23)

In [34]:
print("Unique Kreise now:", hospitals["kreis_code"].nunique())

Unique Kreise now: 397

In [35]:
per_kreis = (
    hospitals
    .groupby("kreis_code")
    .size()
    .reset_index(name="n_standorte")
)

print(per_kreis.shape)

(397, 2)

In [36]:
print(per_kreis.head())

  kreis_code  n_standorte
0      01001            8
1      01002           14
2      01003           12
3      01004            3
4      01051            3

In [37]:
print("\nDistribution of Standorte per Kreis:")
print(per_kreis["n_standorte"].describe())

Distribution of Standorte per Kreis:
count    397.000000
mean       6.083123
std        5.014186
min        1.000000
25%        3.000000
50%        5.000000
75%        8.000000
max       62.000000
Name: n_standorte, dtype: float64

##second - the cleaned version of the file population_by_age_series.csv

In [38]:
pop_2023 = population[population["date"] == "31.12.2023"].copy()

In [39]:
pop_2023 = pop_2023.copy()
for col in ["total_all", "total_male", "total_female",
            "german_all", "german_male", "german_female",
            "foreign_all", "foreign_male", "foreign_female"]:
    pop_2023[col] = pd.to_numeric(pop_2023[col], errors="coerce")

In [40]:
pop_2023 = pop_2023[~pop_2023["kreis_code"].astype(str).str[:2].isin(["02", "11"])].copy() #excluding Berlin and Hamburg

In [41]:
pop_2023 = pop_2023.dropna(subset=["total_all"]).copy()

In [42]:
print(pop_2023.shape)

(8756, 13)

In [43]:
print(pop_2023["kreis_code"].nunique(), "unique Kreise")

398 unique Kreise

In [44]:
print("\nAge group categories:")
for ag in pop_2023["age_group"].unique():
    print(f"  {ag}")

Age group categories:
  unter 3 Jahre
  3 bis unter 6 Jahre
  6 bis unter 10 Jahre
  10 bis unter 15 Jahre
  15 bis unter 18 Jahre
  18 bis unter 20 Jahre
  20 bis unter 25 Jahre
  25 bis unter 30 Jahre
  30 bis unter 35 Jahre
  35 bis unter 40 Jahre
  40 bis unter 45 Jahre
  45 bis unter 50 Jahre
  50 bis unter 55 Jahre
  55 bis unter 60 Jahre
  60 bis unter 65 Jahre
  65 bis unter 70 Jahre
  70 bis unter 75 Jahre
  75 bis unter 80 Jahre
  80 bis unter 85 Jahre
  85 bis unter 90 Jahre
  90 Jahre und mehr
  Insgesamt

In [45]:
age_65_plus = [
    "65 bis unter 70 Jahre",
    "70 bis unter 75 Jahre",
    "75 bis unter 80 Jahre",
    "80 bis unter 85 Jahre",
    "85 bis unter 90 Jahre",
    "90 Jahre und mehr",
]

In [46]:
total_pop = (
    pop_2023[pop_2023["age_group"] == "Insgesamt"]
    [["kreis_code", "kreis_name", "total_all"]]
    .rename(columns={"total_all": "pop_total"})
    .copy()
)
print(total_pop.shape)

(398, 3)

In [47]:
pop_2023["total_all"] = pd.to_numeric(pop_2023["total_all"], errors="coerce")

In [48]:
total_pop.head()

      kreis_code                                  kreis_name  pop_total
35573      01001                 Flensburg, kreisfreie Stadt    96431.0
35595      01002                      Kiel, kreisfreie Stadt   251751.0
35617      01003        Lübeck, kreisfreie Stadt, Hansestadt   217061.0
35639      01004                Neumünster, kreisfreie Stadt    79461.0
35661      01051                         Dithmarschen, Kreis   133514.0

In [49]:
pop_65 = (
    pop_2023[pop_2023["age_group"].isin(age_65_plus)]
    .groupby("kreis_code")["total_all"]
    .sum()
    .reset_index(name="pop_65_plus")
    )
print(pop_65.shape)

(398, 2)

In [50]:
pop_65.head()

  kreis_code  pop_65_plus
0      01001      19299.0
1      01002      48598.0
2      01003      50667.0
3      01004      18230.0
4      01051      34524.0

In [51]:
kreis_pop = total_pop.merge(pop_65, on="kreis_code")

In [52]:
kreis_pop["share_65_plus"] = kreis_pop["pop_65_plus"] / kreis_pop["pop_total"]
print(kreis_pop.head())

  kreis_code                                  kreis_name  pop_total  \
0      01001                 Flensburg, kreisfreie Stadt    96431.0
1      01002                      Kiel, kreisfreie Stadt   251751.0
2      01003        Lübeck, kreisfreie Stadt, Hansestadt   217061.0
3      01004                Neumünster, kreisfreie Stadt    79461.0
4      01051                         Dithmarschen, Kreis   133514.0

   pop_65_plus  share_65_plus
0      19299.0       0.200133
1      48598.0       0.193040
2      50667.0       0.233423
3      18230.0       0.229421
4      34524.0       0.258580

In [53]:
print("\nDistribution of share_65_plus:")
print(kreis_pop["share_65_plus"].describe())

Distribution of share_65_plus:
count    398.000000
mean       0.234228
std        0.031203
min        0.158930
25%        0.214670
50%        0.229441
75%        0.252584
max        0.327816
Name: share_65_plus, dtype: float64

#Stage 4 - the merge of the two datasets for 2023

In [54]:
merged = kreis_pop.merge(per_kreis, on="kreis_code", how="left")

In [55]:
merged["n_standorte"] = merged["n_standorte"].fillna(0).astype(int)

In [56]:
merged["hospitals_per_100k"] = merged["n_standorte"] / merged["pop_total"] * 100_000 #hospitals per 100 thousands people

In [57]:
print(merged.shape)

(398, 7)

In [58]:
print(merged.head())

  kreis_code                                  kreis_name  pop_total  \
0      01001                 Flensburg, kreisfreie Stadt    96431.0
1      01002                      Kiel, kreisfreie Stadt   251751.0
2      01003        Lübeck, kreisfreie Stadt, Hansestadt   217061.0
3      01004                Neumünster, kreisfreie Stadt    79461.0
4      01051                         Dithmarschen, Kreis   133514.0

   pop_65_plus  share_65_plus  n_standorte  hospitals_per_100k
0      19299.0       0.200133            8            8.296087
1      48598.0       0.193040           14            5.561050
2      50667.0       0.233423           12            5.528400
3      18230.0       0.229421            3            3.775437
4      34524.0       0.258580            3            2.246955

In [59]:
print("\n=== Distribution of hospitals_per_100k ===")
print(merged["hospitals_per_100k"].describe())

=== Distribution of hospitals_per_100k ===
count    398.000000
mean       3.400464
std        1.738943
min        0.000000
25%        2.194523
50%        3.059024
75%        4.301908
max       10.313598
Name: hospitals_per_100k, dtype: float64

In [60]:
merged[merged["n_standorte"] == 0]

,kreis_code,kreis_name,pop_total,pop_65_plus,share_65_plus,n_standorte,hospitals_per_100k
174,07338,Rhein-Pfalz-Kreis,155525.0,37103.0,0.238566,0,0.0
286,09573,"Fürth, Landkreis",117617.0,27999.0,0.238052,0,0.0

#Stage 4. Plotting data for 2023

In [61]:
import plotly.express as px

fig = px.scatter(
    merged,
    x="share_65_plus",
    y="hospitals_per_100k",
    hover_name="kreis_name",      
    trendline="ols",              # adds a linear trend line
    title="Hospital access vs. share of population aged 65+ — Germany, 2023",
    labels={
        "share_65_plus":      "Share of population aged 65+",
        "hospitals_per_100k": "Hospital Standorte per 100,000 residents",
    },
    opacity=0.6,                  # for overlapping dots 
)
fig.show()