In [1]:
import pandas as pd

In [4]:
sheet_to_df_map = pd.read_excel("/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/krankenhausverzeichnis_2023.xlsx", sheet_name=None)

In [6]:
df = pd.read_excel("/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/krankenhausverzeichnis_2023.xlsx")

In [7]:
xls = pd.ExcelFile("/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/krankenhausverzeichnis_2023.xlsx")
xls.sheet_names

['Titelblatt',
 'Impressum',
 'Inhalt',
 'Vorbemerkungen',
 ' KHV_2023',
 'RHV_2023',
 'DSB_KHV_2023',
 'DSB_RHV_2023',
 'Land',
 'Kreis',
 'Statistische Ämter']

In [8]:
df = pd.read_excel("/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/krankenhausverzeichnis_2023.xlsx", sheet_name="Kreis")

In [10]:
sheet_to_df_map[" KHV_2023"].head()

,Zurück zum Inhalt,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171
0,Verzeichnis der Krankenhäuser (KHV_2023),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Land,Kreis,Gemeinde,Adresse_Name,Adresse_Name_Standort,Adresse_Strasse_Standort,Adresse_Haus-Nr._Standort,Adresse_Postleitzahl_Standort,Adresse_Ort_Standort,Telefonvorwahl -nummer,...,3750.0,3751.0,3752.0,3753.0,3754.0,3755.0,3756.0,3757.0,3758.0,3759.0
2,01,001,000,DIAKO Krankenhaus gGmbH,DIAKO Krankenhaus gGmbH,Knuthstraße,1,24939,Flensburg,0461 812-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Fachklinik f...,"DIAKO Fachklinik für Psychiatrie, Psychosomati...",Knuthstraße,1,24939,Flensburg,0461 812-1701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Ältere Flensburg,Marienhölzungsweg,8,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
sheet_to_df_map[" KHV_2023"].columns

Index(['Zurück zum Inhalt', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9',
       ...
       'Unnamed: 162', 'Unnamed: 163', 'Unnamed: 164', 'Unnamed: 165',
       'Unnamed: 166', 'Unnamed: 167', 'Unnamed: 168', 'Unnamed: 169',
       'Unnamed: 170', 'Unnamed: 171'],
      dtype='str', length=172)

In [12]:
sheet_to_df_map[" KHV_2023"].shape

(2785, 172)

In [18]:
raw = pd.read_excel(xls, sheet_name=" KHV_2023", header=None)  #solving the issue with the headers
raw.head(10)

,0,1,2,3,4,5,6,7,8,9,...,162,163,164,165,166,167,168,169,170,171
0,Zurück zum Inhalt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Verzeichnis der Krankenhäuser (KHV_2023),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Land,Kreis,Gemeinde,Adresse_Name,Adresse_Name_Standort,Adresse_Strasse_Standort,Adresse_Haus-Nr._Standort,Adresse_Postleitzahl_Standort,Adresse_Ort_Standort,Telefonvorwahl -nummer,...,3750.0,3751.0,3752.0,3753.0,3754.0,3755.0,3756.0,3757.0,3758.0,3759.0
3,01,001,000,DIAKO Krankenhaus gGmbH,DIAKO Krankenhaus gGmbH,Knuthstraße,1,24939,Flensburg,0461 812-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Fachklinik f...,"DIAKO Fachklinik für Psychiatrie, Psychosomati...",Knuthstraße,1,24939,Flensburg,0461 812-1701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Ältere Flensburg,Marienhölzungsweg,8,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Erwachsene Flensburg,Marienhölzungsweg,21,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für KJP (Villa Paletti),Marienhölzungsweg,68,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Psychosomatik Flensburg,Nerongsallee,5,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,01,001,000,Katharinen Hospiz am Park,Katharinen Hospiz am Park,Mühlenstraße,1,24937,Flensburg,0461 503230,...,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = pd.read_excel(xls, sheet_name=" KHV_2023", header=2)  #the right header found
df.head()

,Land,Kreis,Gemeinde,Adresse_Name,Adresse_Name_Standort,Adresse_Strasse_Standort,Adresse_Haus-Nr._Standort,Adresse_Postleitzahl_Standort,Adresse_Ort_Standort,Telefonvorwahl -nummer,...,3750,3751,3752,3753,3754,3755,3756,3757,3758,3759
0,1.0,1.0,0.0,DIAKO Krankenhaus gGmbH,DIAKO Krankenhaus gGmbH,Knuthstraße,1,24939.0,Flensburg,0461 812-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Fachklinik f...,"DIAKO Fachklinik für Psychiatrie, Psychosomati...",Knuthstraße,1,24939.0,Flensburg,0461 812-1701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Ältere Flensburg,Marienhölzungsweg,8,24939.0,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Erwachsene Flensburg,Marienhölzungsweg,21,24939.0,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für KJP (Villa Paletti),Marienhölzungsweg,68,24939.0,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
sheet_to_df_map["Kreis"].head()

,Zurück zum Inhalt,Unnamed: 1,Unnamed: 2
0,Verzeichnis der Kreisschlüssel (Gebietsstand 3...,NaN,NaN
1,"Schlüsselnummer,\n1. und 2. Stelle = Land",Regionale Bezeichnung,Kreisfreie Stadt
2,NaN,NaN,Kreis/Landkreis
3,01001,Kreisfreie Stadt,"Flensburg, Stadt"
4,01002,Kreisfreie Stadt,"Kiel, Landeshauptstadt"

In [25]:
sheet_to_df_map["Kreis"].columns

Index(['Zurück zum Inhalt', 'Unnamed: 1', 'Unnamed: 2'], dtype='str')

In [43]:
csv_path = "/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/population_by_age_kreis.csv"

In [45]:
columns = [
    "date",
    "kreis_code",
    "kreis_name",
    "age_group",
    # "Insgesamt" group (all nationalities):
    "total_all",
    "total_male",
    "total_female",
    # "deutsch" group:
    "german_all",
    "german_male",
    "german_female",
    # "ausländisch" group:
    "foreign_all",
    "foreign_male",
    "foreign_female",
]

population = pd.read_csv(
    csv_path,
    skiprows=8,
    header=None,
    names=columns,
    encoding="latin1",
    sep=";",
)
population.head()

,date,kreis_code,kreis_name,age_group,total_all,total_male,total_female,german_all,german_male,german_female,foreign_all,foreign_male,foreign_female
0,31.12.2024,DG,Deutschland,unter 3 Jahre,2118482,1086772,1031710,1790945,918692,872253,327537,168080,159457
1,31.12.2024,DG,Deutschland,3 bis unter 6 Jahre,2373188,1216863,1156325,2015573,1033511,982062,357615,183352,174263
2,31.12.2024,DG,Deutschland,6 bis unter 10 Jahre,3249024,1664142,1584882,2747672,1405829,1341843,501352,258313,243039
3,31.12.2024,DG,Deutschland,10 bis unter 15 Jahre,3879201,1992159,1887042,3292561,1686601,1605960,586640,305558,281082
4,31.12.2024,DG,Deutschland,15 bis unter 18 Jahre,2355147,1221800,1133347,2000410,1025001,975409,354737,196799,157938

In [ ]:
#there're extra rows under "the kreis_code" and "kreis_name"

In [46]:

population_raw = population.copy()

population = population[population["kreis_code"].astype(str).str.len() == 5].copy()

print(population.shape)

(10362, 13)

In [47]:
print(population["kreis_code"].nunique(), "unique Kreise")

471 unique Kreise

In [ ]:
# The result doesn't sound right: 471 unique:q Kreise