In [1]:
import pandas as pd

In [4]:
sheet_to_df_map = pd.read_excel("/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/krankenhausverzeichnis_2023.xlsx", sheet_name=None)

In [6]:
df = pd.read_excel("/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/krankenhausverzeichnis_2023.xlsx")

In [7]:
xls = pd.ExcelFile("/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/krankenhausverzeichnis_2023.xlsx")
xls.sheet_names

['Titelblatt',
 'Impressum',
 'Inhalt',
 'Vorbemerkungen',
 ' KHV_2023',
 'RHV_2023',
 'DSB_KHV_2023',
 'DSB_RHV_2023',
 'Land',
 'Kreis',
 'Statistische Ämter']

In [8]:
df = pd.read_excel("/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/krankenhausverzeichnis_2023.xlsx", sheet_name="Kreis")

In [10]:
sheet_to_df_map[" KHV_2023"].head()

,Zurück zum Inhalt,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171
0,Verzeichnis der Krankenhäuser (KHV_2023),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Land,Kreis,Gemeinde,Adresse_Name,Adresse_Name_Standort,Adresse_Strasse_Standort,Adresse_Haus-Nr._Standort,Adresse_Postleitzahl_Standort,Adresse_Ort_Standort,Telefonvorwahl -nummer,...,3750.0,3751.0,3752.0,3753.0,3754.0,3755.0,3756.0,3757.0,3758.0,3759.0
2,01,001,000,DIAKO Krankenhaus gGmbH,DIAKO Krankenhaus gGmbH,Knuthstraße,1,24939,Flensburg,0461 812-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Fachklinik f...,"DIAKO Fachklinik für Psychiatrie, Psychosomati...",Knuthstraße,1,24939,Flensburg,0461 812-1701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Ältere Flensburg,Marienhölzungsweg,8,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
sheet_to_df_map[" KHV_2023"].columns

Index(['Zurück zum Inhalt', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9',
       ...
       'Unnamed: 162', 'Unnamed: 163', 'Unnamed: 164', 'Unnamed: 165',
       'Unnamed: 166', 'Unnamed: 167', 'Unnamed: 168', 'Unnamed: 169',
       'Unnamed: 170', 'Unnamed: 171'],
      dtype='str', length=172)

In [12]:
sheet_to_df_map[" KHV_2023"].shape

(2785, 172)

In [18]:
raw = pd.read_excel(xls, sheet_name=" KHV_2023", header=None)  #solving the issue with the headers
raw.head(10)

,0,1,2,3,4,5,6,7,8,9,...,162,163,164,165,166,167,168,169,170,171
0,Zurück zum Inhalt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Verzeichnis der Krankenhäuser (KHV_2023),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Land,Kreis,Gemeinde,Adresse_Name,Adresse_Name_Standort,Adresse_Strasse_Standort,Adresse_Haus-Nr._Standort,Adresse_Postleitzahl_Standort,Adresse_Ort_Standort,Telefonvorwahl -nummer,...,3750.0,3751.0,3752.0,3753.0,3754.0,3755.0,3756.0,3757.0,3758.0,3759.0
3,01,001,000,DIAKO Krankenhaus gGmbH,DIAKO Krankenhaus gGmbH,Knuthstraße,1,24939,Flensburg,0461 812-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Fachklinik f...,"DIAKO Fachklinik für Psychiatrie, Psychosomati...",Knuthstraße,1,24939,Flensburg,0461 812-1701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Ältere Flensburg,Marienhölzungsweg,8,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Erwachsene Flensburg,Marienhölzungsweg,21,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für KJP (Villa Paletti),Marienhölzungsweg,68,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,01,001,000,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Psychosomatik Flensburg,Nerongsallee,5,24939,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,01,001,000,Katharinen Hospiz am Park,Katharinen Hospiz am Park,Mühlenstraße,1,24937,Flensburg,0461 503230,...,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
df.shape

(2783, 172)

In [117]:
df = pd.read_excel(xls, sheet_name=" KHV_2023", header= 2, na_values=["-"])  #the right header found
df.head()

,Land,Kreis,Gemeinde,Adresse_Name,Adresse_Name_Standort,Adresse_Strasse_Standort,Adresse_Haus-Nr._Standort,Adresse_Postleitzahl_Standort,Adresse_Ort_Standort,Telefonvorwahl -nummer,...,3750,3751,3752,3753,3754,3755,3756,3757,3758,3759
0,1.0,1.0,0.0,DIAKO Krankenhaus gGmbH,DIAKO Krankenhaus gGmbH,Knuthstraße,1,24939.0,Flensburg,0461 812-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Fachklinik f...,"DIAKO Fachklinik für Psychiatrie, Psychosomati...",Knuthstraße,1,24939.0,Flensburg,0461 812-1701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Ältere Flensburg,Marienhölzungsweg,8,24939.0,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Erwachsene Flensburg,Marienhölzungsweg,21,24939.0,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für KJP (Villa Paletti),Marienhölzungsweg,68,24939.0,Flensburg,04671 408-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [118]:
df.shape

(2783, 172)

In [129]:
df.columns

Index([                         'Land',                         'Kreis',
                            'Gemeinde',                  'Adresse_Name',
               'Adresse_Name_Standort',      'Adresse_Strasse_Standort',
           'Adresse_Haus-Nr._Standort', 'Adresse_Postleitzahl_Standort',
                'Adresse_Ort_Standort',        'Telefonvorwahl -nummer',
       ...
                                '3750',                          '3751',
                                '3752',                          '3753',
                                '3754',                          '3755',
                                '3756',                          '3757',
                                '3758',                          '3759'],
      dtype='object', length=172)

In [139]:
text_only = [c for c in df.columns if not str(c).isdigit()] # excluding data about bed counts per Fachabteilung/columns named as digits
hospitals = df[text_only].copy()
hospitals.shape

(2783, 22)

In [213]:
hospitals.head()

,Land,Kreis,Gemeinde,Adresse_Name,Adresse_Name_Standort,Adresse_Strasse_Standort,Adresse_Haus-Nr._Standort,Adresse_Postleitzahl_Standort,Adresse_Ort_Standort,Telefonvorwahl -nummer,...,Traeger,T_Name,EinrichtungsTyp,Allgemeine_Notfallversorgung,Spezielle_Notfallversorgung_Schwerverletzte,Spezielle_Notfallversorgung_Kinder,Spezielle_Notfallversorgung_Spezial,Spezielle_Notfallversorgung_Schlaganfall,Spezielle_Notfallversorgung_Durchblutung_Herz,INSG
0,1.0,1.0,0.0,DIAKO Krankenhaus gGmbH,DIAKO Krankenhaus gGmbH,Knuthstraße,1,24939.0,Flensburg,0461 812-0,...,2.0,DIAKO Krankenhaus gGmbH,2.0,2.0,1.0,1.0,2.0,1.0,2.0,400.0
1,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Fachklinik f...,"DIAKO Fachklinik für Psychiatrie, Psychosomati...",Knuthstraße,1,24939.0,Flensburg,0461 812-1701,...,2.0,DIAKO Nordfriesland gGmbH,2.0,0.0,2.0,2.0,2.0,2.0,2.0,87.0
2,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Ältere Flensburg,Marienhölzungsweg,8,24939.0,Flensburg,04671 408-0,...,2.0,DIAKO Nordfriesland gGmbH,2.0,0.0,2.0,2.0,2.0,2.0,2.0,0.0
3,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für Erwachsene Flensburg,Marienhölzungsweg,21,24939.0,Flensburg,04671 408-0,...,2.0,DIAKO Nordfriesland gGmbH,2.0,0.0,2.0,2.0,2.0,2.0,2.0,0.0
4,1.0,1.0,0.0,DIAKO Nordfriesland gGmbH - DIAKO Tagesklinike...,DIAKO Tagesklinik für KJP (Villa Paletti),Marienhölzungsweg,68,24939.0,Flensburg,04671 408-0,...,2.0,DIAKO Nordfriesland gGmbH,2.0,0.0,2.0,2.0,2.0,2.0,2.0,0.0

In [238]:
hospitals["EinrichtungsTyp"].value_counts(dropna=False)

EinrichtungsTyp
2.0    2352
3.0     108
1.0      86
5.0       5
Name: count, dtype: int64

In [239]:
#1 -Hochschulklinik , 2 -Plankrankenhaus , 3- Krankenhaus mit Versorgungsvertrag, 4- Krankenhaus ohne Versorgungsvertrag , 5- Bundeswehrkrankenhäuser

In [240]:
# keeping every type of a hospital, except for a private clinic
hospitals_full_type = hospitals.copy()    # a copy of the pre-filter version

hospitals = hospitals[hospitals["EinrichtungsTyp"].isin([1, 2, 3, 5])].copy()

print(hospitals["EinrichtungsTyp"].value_counts(dropna=False))

(2551, 22)
EinrichtungsTyp
2.0    2352
3.0     108
1.0      86
5.0       5
Name: count, dtype: int64

In [250]:
print(hospitals.shape)

(2551, 22)

In [251]:
#Looking at population csv

In [252]:
csv_path = "/Users/nataliam/Documents/Claude/Projects/German hospitals/data/raw/population_by_age_kreis_series.csv"

In [253]:
columns = [
    "date",
    "kreis_code",
    "kreis_name",
    "age_group",
    # "Insgesamt" group (all nationalities):
    "total_all",
    "total_male",
    "total_female",
    # "deutsch" group:
    "german_all",
    "german_male",
    "german_female",
    # "ausländisch" group:
    "foreign_all",
    "foreign_male",
    "foreign_female",
]

population = pd.read_csv(
    csv_path,
    skiprows=8,
    header=None,
    names=columns,
    encoding="latin1",
    sep=";",
    na_values=["-"]
)
population.head()

,date,kreis_code,kreis_name,age_group,total_all,total_male,total_female,german_all,german_male,german_female,foreign_all,foreign_male,foreign_female
0,31.12.2011,DG,Deutschland,unter 3 Jahre,2007147,1028888,978259,1920373,984386,935987,86774,44502,42272
1,31.12.2011,DG,Deutschland,3 bis unter 6 Jahre,2056777,1055634,1001143,1969110,1010506,958604,87667,45128,42539
2,31.12.2011,DG,Deutschland,6 bis unter 10 Jahre,2819988,1446549,1373439,2690250,1379822,1310428,129738,66727,63011
3,31.12.2011,DG,Deutschland,10 bis unter 15 Jahre,3889094,1994982,1894112,3604302,1849308,1754994,284792,145674,139118
4,31.12.2011,DG,Deutschland,15 bis unter 18 Jahre,2369946,1216198,1153748,2157004,1106559,1050445,212942,109639,103303

In [254]:
#there're extra rows under "the kreis_code" and "kreis_name", e.g. Deutschland, that I have to get rid of

In [255]:

population_raw = population.copy()

population = population[population["kreis_code"].astype(str).str.len() == 5].copy()

print(population.shape)

(41448, 13)

In [256]:
print(population["kreis_code"].nunique(), "unique Kreise")

471 unique Kreise

In [257]:
# The result doesn't sound right: 471 unique Kreise is too many.

In [258]:
population_new= population.dropna(subset=['total_all'])

In [259]:
print(population_new["kreis_code"].nunique(), "unique Kreise")

401 unique Kreise